version: '3'
services:
  nginx-proxy:
    image: nginx:${NGINX_VERSION:-latest}
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_PROXY:-nginx-proxy}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen:${DOCKER_GEN_VERSION}
    command: -notify-sighup ${NGINX_PROXY:-nginx-proxy} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_PROXY:-nginx-proxy}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

  ghost:
    build: ./ghost
    container_name: ${GHOST_BLOG:-ghost-blog}
    restart: always
    volumes:
      - ${GHOST_FILES_PATH:-./data}/ghost-content:/var/lib/ghost/content
    environment:
      - url=${URL:-localhost}
      - database__client=mysql
      - database__connection__host=${MYSQL_DB:-mysql}
      - database__connection__user=${DB_USER:-default_user}
      - database__connection__password=${DB_PASSWORD:-default_password}
      - database__connection__database=${DB_GHOST_DATABASE:-default_database}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT:-2368}
      - LETSENCRYPT_HOST=${LETS_ENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST:-true}
#      - mail__transport=SMTP
#      - mail__options__service=Mailgun
#      - mail__options__auth__user=${MAILGUN_USER}
#      - mail__options__auth__pass=${MAILGUN_PASSWORD}
    depends_on:
      - mysql
    logging:
      driver: ${GHOST_BLOG_LOG_DRIVER:-json-file}
      options:
        max-size: ${GHOST_BLOG_LOG_MAX_SIZE:-2m}
        max-file: ${GHOST_BLOG_LOG_MAX_FILE:-10}

  mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    container_name: ${MYSQL_DB:-mysql}
    volumes:
      - ${MYSQL_FILES_PATH:-./data}/ghost-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_GHOST_DATABASE:-default_database}
      - MYSQL_USER=${DB_USER:-default_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-default_password}
    restart: unless-stopped
    logging:
      driver: ${MYSQL_DB_LOG_DRIVER:-json-file}
      options:
        max-size: ${MYSQL_DB_LOG_MAX_SIZE:-2m}
        max-file: ${MYSQL_DB_LOG_MAX_FILE:-10}

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
